### ISSUE TITLE
The example Voronoi relaxation is a bit different than Lloyd’s algorithm on Wikipedia.

### ISSUE THREAD

**Issue by issuefiler** [JCash/voronoi#71]
## The example Voronoi relaxation

https://github.com/JCash/voronoi/blob/7dc36e70bd445123ba58a295db2d954757e25b6d/README.md?plain=1#L136-L164

```C
 void relax_points(const jcv_diagram* diagram, jcv_point* points) 
 { 
     const jcv_site* sites = jcv_diagram_get_sites(diagram); 
     for( int i = 0; i < diagram->numsites; ++i ) 
     { 
         const jcv_site* site = &sites[i]; 
         jcv_point sum = site->p; 
         int count = 1; 
  
         const jcv_graphedge* edge = site->edges; 
  
         while( edge ) 
         { 
             sum.x += edge->pos[0].x; 
             sum.y += edge->pos[0].y; 
             ++count; 
             edge = edge->next; 
         } 
  
         points[site->index].x = sum.x / count; 
         points[site->index].y = sum.y / count; 
     } 
 } 
```

## [Lloyd’s algorithm](https://en.wikipedia.org/wiki/Lloyd%27s_algorithm)

>  It then repeatedly executes the following relaxation step:
>
> [The Voronoi diagram](https://en.wikipedia.org/wiki/Voronoi_diagram) of the `k` sites is computed.
> Each cell of the Voronoi diagram is integrated, and the **centroid** is computed.
> Each site is then moved to the centroid of its Voronoi cell.

# Question

 [Lloyd’s algorithm on Wikipedia](https://en.wikipedia.org/wiki/Lloyd%27s_algorithm) computes the centroids of Voronoi cells, while the example Voronoi relaxation on the `README` looks like it’s averaging vertices instead of computing centroids. [The two would be similar in position, but not the same.](https://stackoverflow.com/a/65891206/4510033)

 Speaking of the results, how would it be different compared to [Lloyd’s on Wikipedia](https://en.wikipedia.org/wiki/Lloyd%27s_algorithm)? I’m trying to evenly spread out some points and not sure which way I should follow to get more accurate results.

**Comment by JCash** [comment]
The example relaxation code is calculating the center of the polygon.
It's an easy and fast way to do it, but there are probably others as well.

When I refer to Lloyds algorithm, I'm referring to the voronoi algorithm, not the way to relax points, since that may be done in infinite number of ways.

I think "spreading out" and "accurate" doesn't really make much sense in all cases.
You may very well write a separate relaxation function which _doesn't_ use the center of the polygon,
but instead takes into account forces, friction or mass or other things that you care about.

It's just an example. Feel free to write your own that fits your use case.
